// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Search_Engine.Data;

#nullable disable

namespace Search_Engine.Migrations
{
    [DbContext(typeof(SearchEngineContext))]
    [Migration("20250506131916_start")]
    partial class start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Search_Engine.Models.Mapping", b =>
                {
                    b.Property<int>("Mapping_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Mapping_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapping_ID"));

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("Frequency");

                    b.Property<int>("URL_ID")
                        .HasColumnType("int")
                        .HasColumnName("URL_ID");

                    b.Property<int>("Word_ID")
                        .HasColumnType("int")
                        .HasColumnName("Word_ID");

                    b.HasKey("Mapping_ID");

                    b.HasIndex("URL_ID");

                    b.HasIndex("Word_ID");

                    b.ToTable("Mapping", (string)null);
                });

            modelBuilder.Entity("Search_Engine.Models.Urls", b =>
                {
                    b.Property<int>("URL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("URL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("URL_ID"));

                    b.Property<double>("PageRank")
                        .HasColumnType("float")
                        .HasColumnName("PageRank");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URL");

                    b.HasKey("URL_ID");

                    b.ToTable("URLs", (string)null);
                });

            modelBuilder.Entity("Search_Engine.Models.Word", b =>
                {
                    b.Property<int>("Word_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Word_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Word_ID"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Word");

                    b.HasKey("Word_ID");

                    b.ToTable("Word", (string)null);
                });

            modelBuilder.Entity("Search_Engine.Models.Mapping", b =>
                {
                    b.HasOne("Search_Engine.Models.Urls", "Url")
                        .WithMany()
                        .HasForeignKey("URL_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Search_Engine.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("Word_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");

                    b.Navigation("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
