version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Search_Engine_v2/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=SearchEngineDb;User=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - search-engine-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - search-engine-network

networks:
  search-engine-network:
    driver: bridge

volumes:
  sqldata: